name: DropGox CI/CD

on:
  push:
    branches:
      - main
      - develop
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
      - develop


jobs:
  build:
    name: Build DropGox
    runs-on: debian  # Using self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.0"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Build application
        run: go build -o dropgox-backend main.go

  docker:
    name: Build & Push Docker Image
    runs-on: debian
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker Image Version
        id: vars
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}  # Extracts the tag name
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            VERSION="latest"
          else
            VERSION="dev"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Docker Image Tag: $VERSION"

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dropgox:$VERSION .
          docker push ${{ secrets.DOCKER_USERNAME }}/dropgox:$VERSION
